name: Build wheels

on: [push, pull_request]

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04, windows-latest, macos-latest]

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.9'

      - name: Install cibuildwheel
        run: pip install cibuildwheel==2.3.0

      - name: Build wheels
        run: cibuildwheel --output-dir wheelhouse
        env:
          CIBW_BUILD: "cp39-*"  # 指定 Python 版本
          CIBW_ARCHS: "auto"    # 自动检测架构

      - uses: actions/upload-artifact@v3
        with:
          path: ./wheelhouse/*.whl
          name: wheels

  upload_pypi:
    needs: build_wheels
    runs-on: ubuntu-latest
    # if: github.event_name == 'push'

    steps:
      - uses: actions/download-artifact@v3
        with:
          name: wheels
          path: wheelhouse

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@v1.6.4
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}
          skip_existing: true
