name: Pip

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        platform: [ubuntu-18.04, ubuntu-16.04, macos-latest, windows-latest]
        python-version: ["3.8", "3.9", "3.10"]

    runs-on: ${{ matrix.platform }}

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true

    - uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Add requirements
      run: |
          python -m pip install --upgrade pybind11 wheel setuptools twine

    - name: Build and install
      run: |
          cd python
          python3 setup.py build
          python setup.py sdist bdist_wheel

    - name: Upload to pypi
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: pypi-AgEIcHlwaS5vcmcCJGQ1YWE2OWQ1LTg5NDctNDE3ZS04OTliLWU4NDk3NWUzZTg2YQACKlszLCJlZDlkYWFmNi0yNWQ3LTQ5NTItYjQzYy04Y2RmYjZhZmMxYmQiXQAABiCUi5zEW0NI1K49kWzpSF41RlbGy5PO0l9SpS5w-lcQ6A
      run: |
          cd python
          twine upload --verbose dist/*
