name: Pip

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        # platform: [ubuntu-latest, macos-latest, windows-latest]
        platform: [ubuntu-latest]
        python-version: ["3.9"]

    runs-on: ${{ matrix.platform }}

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true

    - uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.x'

    - name: Add requirements
      run: |
        python -m pip install --upgrade pip
        pip install pybind11 setuptools wheel twine

    - name: Build and install
      run: |
        cd python
        python setup.py build
        python setup.py sdist bdist_wheel

#    - name: Upload to pypi
#      env:
#        TWINE_USERNAME: __token__
#        TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
#      run: |
#        twine check dist/*
#        twine upload --verbose dist/*
